#!/usr/bin/env python3
"""
Build quant_config_compare_fig9.csv for 7B_MVM1 (batch=1).

Reads operator_latency_detailed.csv (generated by extract_all.py) and
produces a table of baseline / best latency (cycles) across all
quantisation configs × Q-configs.

Output: fig9/fig9.csv  (subdirectory relative to this script)
"""

import csv
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
INPUT_CSV  = SCRIPT_DIR / "operator_latency_detailed.csv"
OUTPUT_DIR = SCRIPT_DIR / "fig9"
OUTPUT_DIR.mkdir(exist_ok=True)
OUTPUT_CSV = OUTPUT_DIR / "fig9.csv"

# Q-config name → (group_k, group_n)
Q_CONFIGS = {
    "Q1": ("16",  "1"),
    "Q2": ("32",  "1"),
    "Q3": ("16",  "16"),
    "Q4": ("32",  "32"),
    "Q5": ("64",  "64"),
    "Q6": ("128", "128"),
}

# (quant_method, bitwidth) → display label
QUANT_CONFIG_LABELS = [
    ("w_a",    "D4S8",  "W4A4S8 (W-A)"),
    ("w_a",    "D8S16", "W8A8S16 (W-A)"),
    ("w_only", "D4S8",  "W4A16S8 (W-Only)"),
    ("w_only", "D8S16", "W8A16S16 (W-Only)"),
]


def main():
    # Load and index rows for 7B_MVM1 batch=1
    idx = {}
    with open(INPUT_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["model_size"] != "7B" or row["op_name"] != "7B_MVM1" or row["M"] != "1":
                continue
            key = (row["quant_method"], row["bitwidth"], row["group_k"], row["group_n"])
            idx[key] = row

    # Build output rows
    out_rows = []
    for method, bitwidth, label in QUANT_CONFIG_LABELS:
        for q_name, (gk, gn) in Q_CONFIGS.items():
            r = idx.get((method, bitwidth, gk, gn), {})
            out_rows.append({
                "quant_config":     label,
                "Q":                q_name,
                "baseline_latency": r.get("baseline_latency", ""),
                "best_latency":     r.get("best_latency",     ""),
            })

    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f, fieldnames=["quant_config", "Q", "baseline_latency", "best_latency"]
        )
        writer.writeheader()
        writer.writerows(out_rows)

    print(f"Written {len(out_rows)} rows to {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
