import os
import re
import csv
from pathlib import Path
from typing import Dict, Tuple, Optional

SCRIPT_DIR = Path(__file__).resolve().parent

# FP16 baseline logs: flexq_ndp/scripts/fp16_baseline/for_quant/
FP16_BASE_DIR = SCRIPT_DIR.parents[1] / "fp16_baseline" / "for_quant"

# operator_latency_detailed.csv generated by extract_rebuttal_to_csv.py
QUANT_CSV_PATH = SCRIPT_DIR.parent / "3_single_op_with_predictor" / "operator_latency_detailed.csv"

# quant_latency log dir (parsed inline – no pre-built CSV needed)
QUANT_ACT_LOG_DIR = SCRIPT_DIR.parent / "3_single_op_with_predictor" / "quant_latency" / "log"
# 层名称和对应的log文件映射
# 格式: (层名称, 对应的log文件名)
# 相同大小的层共享同一个log文件

# 7B和13B模型的层
LAYERS_7B_13B = [
    ('q_emb_add', '_q_emb_add'),
    ('q_emb_mul', '_q_emb_mul'),
    ('k_emb_add', '_k_emb_add'),
    ('k_emb_mul', '_k_emb_mul'),
    ('q_gen', '_qkvo_gen'),      # Q, K, V, O projection大小相同
    ('k_gen', '_qkvo_gen'),      # 都参考 _qkvo_gen.log
    ('v_gen', '_qkvo_gen'),
    ('out_proj', '_qkvo_gen'),
    ('qk', '_qk'),
    ('softmax', '_softmax'),
    ('kv', '_kv'),
    ('out_add', '_out_add'),
    ('out_rms_norm', '_out_rms_norm'),
    ('up', '_upgate'),           # Up和Gate projection大小相同
    ('gate', '_upgate'),         # 都参考 _upgate.log
    ('up_add', '_up_add'),       # Up和Gate的输出相加
    ('down', '_down'),
    ('down_add', '_down_add')
]

# 34B模型的层（有所不同，K和V单独生成）
LAYERS_34B = [
    ('q_emb_add', '_q_emb_add'),
    ('q_emb_mul', '_q_emb_mul'),
    ('k_emb_add', '_k_emb_add'),
    ('k_emb_mul', '_k_emb_mul'),
    ('q_gen', '_qo_gen'),        # Q和O projection大小相同
    ('out_proj', '_qo_gen'),     # 都参考 _qo_gen.log
    ('qk', '_qk'),
    ('softmax', '_softmax'),
    ('k_gen', '_kv_gen'),        # K和V projection大小相同
    ('v_gen', '_kv_gen'),        # 都参考 _kv_gen.log
    ('kv', '_kv'),
    ('out_add', '_out_add'),
    ('out_rms_norm', '_out_rms_norm'),
    ('up', '_upgate'),           # Up和Gate projection大小相同
    ('gate', '_upgate'),         # 都参考 _upgate.log
    ('up_add', '_up_add'),       # Up和Gate的输出相加
    ('down', '_down'),
    ('down_add', '_down_add')
]

# Final层（只执行一次）
FINAL_LAYERS = [
    ('final_rms_norm', '_final_rms_norm'),
    ('final_proj', '_final_proj')
]

# 模型重复次数
REPEAT_TIMES = {
    7: 32,
    13: 40,
    34: 50  # 根据Llama2 34B的架构，假设是48层
}

# 34B模型的额外固定延迟（用于特殊处理，如GQA等）
# EXTRA_LATENCY_34B = 37748736  # cycles
EXTRA_LATENCY_34B = (68-32) * 1024**3 / 32 / 64 * 2

# 全局缓存：存储从CSV读取的量化算子延迟
_quant_latency_cache = {}

# 全局缓存：存储w_a量化时的激活量化额外延迟
_quant_act_latency_cache = {}
# 格式: {model_size: {stage: {layer_name: op_name}}}
OP_NAME_MAPPING = {
    7: {
        'prefill': {
            'q_gen': 'MM1', 'k_gen': 'MM1', 'v_gen': 'MM1', 'out_proj': 'MM1',
            'up': 'MM2', 'gate': 'MM2',
            'down': 'MM3'
        },
        'decode': {
            'q_gen': 'MVM1', 'k_gen': 'MVM1', 'v_gen': 'MVM1', 'out_proj': 'MVM1',
            'up': 'MVM2', 'gate': 'MVM2',
            'down': 'MVM3'
        }
    },
    13: {
        'prefill': {
            'q_gen': 'MM1', 'k_gen': 'MM1', 'v_gen': 'MM1', 'out_proj': 'MM1',
            'up': 'MM2', 'gate': 'MM2',
            'down': 'MM3'
        },
        'decode': {
            'q_gen': 'MVM1', 'k_gen': 'MVM1', 'v_gen': 'MVM1', 'out_proj': 'MVM1',
            'up': 'MVM2', 'gate': 'MVM2',
            'down': 'MVM3'
        }
    },
    34: {
        'prefill': {
            'q_gen': 'MM1', 'out_proj': 'MM1',
            'k_gen': 'MM2', 'v_gen': 'MM2',
            'up': 'MM3', 'gate': 'MM3',
            'down': 'MM4'
        },
        'decode': {
            'q_gen': 'MVM1', 'out_proj': 'MVM1',
            'k_gen': 'MVM2', 'v_gen': 'MVM2',
            'up': 'MVM3', 'gate': 'MVM3',
            'down': 'MVM4'
        }
    }
}

# 全局缓存：存储从CSV读取的量化算子延迟
_quant_latency_cache = {}

# 全局缓存：存储w_a量化时的激活量化额外延迟
_quant_act_latency_cache = {}


def _parse_quant_act_operator_name(operator_name):
    """从算子名称中提取 model_size, op_name (ported from parse_quant_latency.py)"""
    mm_pat = re.compile(r'^(\d+B)_MM(\d+)_(\d+)_(\d+)_(\d+)$')
    m = mm_pat.match(operator_name)
    if m:
        model_size = m.group(1)
        op_name = f"{model_size}_MM{m.group(2)}"
        return model_size, op_name

    mvm_pat1 = re.compile(r'^(\d+B)_MVM(\d+)_(\d+)_(\d+)_(\d+)$')
    m = mvm_pat1.match(operator_name)
    if m:
        model_size = m.group(1)
        op_name = f"{model_size}_MVM{m.group(2)}_{m.group(3)}"
        return model_size, op_name

    mvm_pat2 = re.compile(r'^(\d+B)_MVM(\d+)_B(\d+)_\d+_(\d+)_(\d+)$')
    m = mvm_pat2.match(operator_name)
    if m:
        model_size = m.group(1)
        batch = m.group(3)
        op_name = f"{model_size}_MVM{m.group(2)}_B{batch}_{batch}"
        return model_size, op_name

    return None, None


def load_quant_act_latency_from_logs():
    """从 QUANT_ACT_LOG_DIR 日志文件中解析激活量化额外延迟到缓存（集成自 parse_quant_latency.py）"""
    global _quant_act_latency_cache
    if _quant_act_latency_cache:
        return

    configs = [
        ('w_a',    'D4S8', 16, 1),
        ('w_a',    'D4S8', 32, 1),
        ('w_only', 'D4S8', 16, 1),
        ('w_only', 'D4S8', 32, 1),
    ]

    for log_path in sorted(QUANT_ACT_LOG_DIR.glob('*.log')):
        stem = log_path.stem
        if stem.startswith('alex_') or stem.startswith('res18_') or stem.startswith('resnet_'):
            continue

        model_size, op_name = _parse_quant_act_operator_name(stem)
        if model_size is None:
            continue

        try:
            content = log_path.read_text(encoding='utf-8')
        except Exception as e:
            print(f"Warning: could not read {log_path}: {e}")
            continue

        lines = content.split('\n')
        config_idx = 0
        for i, line in enumerate(lines):
            if '==========' in line and 'w_' in line:
                if config_idx >= len(configs):
                    break
                quant_method, bitwidth, group_k, group_n = configs[config_idx]

                baseline_lat1 = baseline_lat2 = lat1 = lat2 = None

                if i + 1 < len(lines):
                    mb = re.search(r'baseline lat all:\s*(\d+),\s*baseline lat original:\s*(\d+)', lines[i + 1])
                    if mb:
                        baseline_lat1, baseline_lat2 = int(mb.group(1)), int(mb.group(2))

                if i + 2 < len(lines):
                    ml = re.search(r'lat all:\s*(\d+),\s*lat original:\s*(\d+)', lines[i + 2])
                    if ml:
                        lat1, lat2 = int(ml.group(1)), int(ml.group(2))

                if None not in (baseline_lat1, baseline_lat2, lat1, lat2):
                    key = (model_size, op_name, quant_method, bitwidth, str(group_k), str(group_n))
                    _quant_act_latency_cache[key] = {
                        'baseline_lat1': baseline_lat1,
                        'baseline_lat2': baseline_lat2,
                        'best_lat1': lat1,
                        'best_lat2': lat2,
                    }

                config_idx += 1


def load_quant_latency_csv():
    """加载量化算子延迟CSV文件到缓存"""
    global _quant_latency_cache
    if _quant_latency_cache:
        return  # 已经加载过了
    
    try:
        with open(QUANT_CSV_PATH, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                model_size = row['model_size']
                op_name = row['op_name']
                quant_method = row['quant_method']
                bitwidth = row['bitwidth']
                group_k = row['group_k']
                group_n = row['group_n']
                baseline_lat = row['baseline_latency']
                best_lat = row['best_latency']
                
                # 构建缓存键
                key = (model_size, op_name, quant_method, bitwidth, group_k, group_n)
                
                # 存储延迟（转换为int，跳过空值）
                if baseline_lat and best_lat:
                    _quant_latency_cache[key] = {
                        'baseline': int(float(baseline_lat)),
                        'best': int(float(best_lat))
                    }
    except Exception as e:
        print(f"Error loading quantization CSV: {e}")


def get_quant_latency(model_size: int, op_name: str, quant_method: str, 
                      bitwidth: str, group_k: int, group_n: int, 
                      batch_size: Optional[int] = None) -> Tuple[Optional[int], Optional[int]]:
    """
    从缓存中获取量化算子的延迟
    Args:
        batch_size: 如果指定，将查找带_B{batch_size}后缀的算子
    Returns: (baseline_latency, best_latency)
    """
    # 确保CSV已加载
    load_quant_latency_csv()
    
    # 如果指定了batch_size，先尝试查找带batch_size后缀的算子
    if batch_size is not None and batch_size > 1:
        op_name_with_bs = f"{op_name}_B{batch_size}"
        key = (f"{model_size}B", f"{model_size}B_{op_name_with_bs}", quant_method, bitwidth, str(group_k), str(group_n))
        if key in _quant_latency_cache:
            return _quant_latency_cache[key]['baseline'], _quant_latency_cache[key]['best']
    
    # 否则查找默认的算子（batch_size=1）
    key = (f"{model_size}B", f"{model_size}B_{op_name}", quant_method, bitwidth, str(group_k), str(group_n))
    
    if key in _quant_latency_cache:
        baseline, best = _quant_latency_cache[key]['baseline'], _quant_latency_cache[key]['best']
        # 如果指定了batch_size但没有找到对应的算子，用batch_size缩放延迟
        if batch_size is not None and batch_size > 1:
            baseline = baseline * batch_size if baseline else None
            best = best * batch_size if best else None
        return baseline, best
    else:
        return None, None


def get_quant_act_latency(model_size: int, op_name: str, quant_method: str,
                          bitwidth: str, group_k: int, group_n: int,
                          batch_size: Optional[int] = None) -> Tuple[int, int, int, int]:
    """
    从缓存中获取激活量化的额外延迟（baseline和best各有lat1和lat2）
    Args:
        batch_size: 如果指定，将查找带_B{batch_size}_{batch_size}或_1后缀的算子
    Returns: (baseline_lat1, baseline_lat2, best_lat1, best_lat2)
    """
    # 确保日志已加载
    load_quant_act_latency_from_logs()
    
    # 构建算子名称
    # 对于MVM算子：batch_size=1时后缀是_1，batch_size>1时后缀是_B{bs}_{bs}
    # 对于MM算子：没有batch_size后缀
    if batch_size is not None and batch_size > 1:
        # 尝试batch_size特定的算子名 (例如: MVM1_B2_2, MVM1_B16_16)
        op_name_with_bs = f"{op_name}_B{batch_size}_{batch_size}"
        key = (f"{model_size}B", f"{model_size}B_{op_name_with_bs}", quant_method, bitwidth, str(group_k), str(group_n))
        if key in _quant_act_latency_cache:
            data = _quant_act_latency_cache[key]
            return data['baseline_lat1'], data['baseline_lat2'], data['best_lat1'], data['best_lat2']
    
    # 查找batch_size=1的算子或MM算子
    # 对于MVM算子，batch_size=1时名称是 MVM1_1
    # 对于MM算子，直接是 MM1
    if 'MVM' in op_name:
        op_name_bs1 = f"{op_name}_1"
    else:
        op_name_bs1 = op_name
    
    key = (f"{model_size}B", f"{model_size}B_{op_name_bs1}", quant_method, bitwidth, str(group_k), str(group_n))
    
    if key in _quant_act_latency_cache:
        data = _quant_act_latency_cache[key]
        baseline_lat1 = data['baseline_lat1']
        baseline_lat2 = data['baseline_lat2']
        best_lat1 = data['best_lat1']
        best_lat2 = data['best_lat2']
        
        # 如果指定了batch_size但没有找到batch_size特定的算子，用batch_size缩放延迟
        # 注意：根据CSV数据，不同batch_size的lat1/lat2并不是严格线性关系，
        # 但如果找不到对应的batch_size数据，我们用线性估算
        if batch_size is not None and batch_size > 1:
            baseline_lat1 = baseline_lat1 * batch_size
            baseline_lat2 = baseline_lat2 * batch_size
            best_lat1 = best_lat1 * batch_size
            best_lat2 = best_lat2 * batch_size
        
        return baseline_lat1, baseline_lat2, best_lat1, best_lat2
    else:
        return 0, 0, 0, 0


def read_latency_from_log(log_file_path):
    """从log文件中读取baseline result延迟"""
    try:
        with open(log_file_path, 'r') as f:
            for line in f:
                if 'baseline result:' in line:
                    # 提取baseline result后的数值
                    latency = int(line.split('baseline result:')[1].strip())
                    return latency
    except FileNotFoundError:
        print(f"Warning: Log file not found: {log_file_path}")
        return 0
    except Exception as e:
        print(f"Error reading {log_file_path}: {e}")
        return 0
    return 0


def calculate_e2e_latency(model_size, stage, quant_config=None, batch_size=1):
    """
    计算端到端延迟
    Args:
        model_size: 模型大小 (7, 13, 34)
        stage: 阶段 ('prefill' 或 'decode')
        quant_config: 量化配置字典，包含 'method', 'bitwidth', 'group_k', 'group_n'
                     如果为None，则使用FP16延迟
        batch_size: decode阶段的batch_size (1, 2, 4, 8, 16, 32, 64)
    Returns:
        dict: {'baseline': baseline_latency, 'best': best_latency} 或 {'fp16': fp16_latency}
    """
    # 构建目录路径
    if stage == 'decode':
        stage_dir = 'decode_tk32'
    else:
        stage_dir = stage
    
    base_dir = str(FP16_BASE_DIR / f"llama2_{model_size}B_{stage_dir}")
    log_dir = os.path.join(base_dir, 'log')
    
    if not os.path.exists(log_dir):
        print(f"Error: Directory not found: {log_dir}")
        return {'fp16': 0} if quant_config is None else {'baseline': 0, 'best': 0}
    
    # 选择对应的层列表
    if model_size in [7, 13]:
        layers = LAYERS_7B_13B
    else:  # 34B
        layers = LAYERS_34B
    
    # 获取重复次数
    repeat_times = REPEAT_TIMES[model_size]
    
    # 初始化延迟计数器
    if quant_config:
        total_baseline = 0
        total_best = 0
        total_baseline_act_lat1 = 0  # baseline算子的激活量化额外延迟lat1
        total_baseline_act_lat2 = 0  # baseline算子的激活量化额外延迟lat2
        total_best_act_lat1 = 0      # best算子的激活量化额外延迟lat1
        total_best_act_lat2 = 0      # best算子的激活量化额外延迟lat2
        config_str = f"{quant_config['method']}_{quant_config['bitwidth']}_{quant_config['group_k']}_{quant_config['group_n']}"
    else:
        total_latency = 0
        config_str = "FP16"
    
    # 添加batch_size信息
    if stage == 'decode' and batch_size > 1:
        config_str += f"_BS{batch_size}"
    
    # 计算重复层的延迟
    print(f"\n{'='*80}")
    print(f"Model: Llama2-{model_size}B, Stage: {stage}, Config: {config_str}")
    print(f"{'='*80}")
    
    for layer_name, log_name in layers:
        # 判断该层是否需要使用量化延迟
        if quant_config and layer_name in OP_NAME_MAPPING[model_size][stage]:
            op_name = OP_NAME_MAPPING[model_size][stage][layer_name]
            # 对decode阶段传入batch_size
            bs = batch_size if stage == 'decode' else None
            baseline_lat, best_lat = get_quant_latency(
                model_size, op_name, 
                quant_config['method'], quant_config['bitwidth'],
                quant_config['group_k'], quant_config['group_n'],
                batch_size=bs
            )
            
            if baseline_lat and best_lat:
                layer_baseline = baseline_lat * repeat_times
                layer_best = best_lat * repeat_times
                total_baseline += layer_baseline
                total_best += layer_best
                
                # 获取激活量化额外延迟（baseline和best各有lat1和lat2）
                baseline_act_lat1, baseline_act_lat2, best_act_lat1, best_act_lat2 = get_quant_act_latency(
                    model_size, op_name,
                    quant_config['method'], quant_config['bitwidth'],
                    quant_config['group_k'], quant_config['group_n'],
                    batch_size=bs
                )
                layer_baseline_act_lat1 = baseline_act_lat1 * repeat_times
                layer_baseline_act_lat2 = baseline_act_lat2 * repeat_times
                layer_best_act_lat1 = best_act_lat1 * repeat_times
                layer_best_act_lat2 = best_act_lat2 * repeat_times
                total_baseline_act_lat1 += layer_baseline_act_lat1
                total_baseline_act_lat2 += layer_baseline_act_lat2
                total_best_act_lat1 += layer_best_act_lat1
                total_best_act_lat2 += layer_best_act_lat2
                
                print(f"{layer_name:20s}: baseline={baseline_lat:12,} x {repeat_times} = {layer_baseline:15,}, "
                      f"best={best_lat:12,} x {repeat_times} = {layer_best:15,}")
            else:
                # 如果量化延迟不存在，回退到FP16
                log_file = os.path.join(log_dir, f"{log_name}.log")
                latency = read_latency_from_log(log_file)
                # 对于decode阶段，需要乘以batch_size
                if stage == 'decode' and batch_size > 1:
                    latency = latency * batch_size
                layer_total = latency * repeat_times
                total_baseline += layer_total
                total_best += layer_total
                print(f"{layer_name:20s}: {latency:12,} cycles x {repeat_times} = {layer_total:15,} (FP16 fallback)")
        else:
            # FP16延迟
            log_file = os.path.join(log_dir, f"{log_name}.log")
            latency = read_latency_from_log(log_file)
            # 对于decode阶段，需要乘以batch_size
            if stage == 'decode' and batch_size > 1:
                latency = latency * batch_size
            layer_total = latency * repeat_times
            if quant_config:
                total_baseline += layer_total
                total_best += layer_total
                print(f"{layer_name:20s}: {latency:12,} cycles x {repeat_times} = {layer_total:15,}")
            else:
                total_latency += layer_total
                print(f"{layer_name:20s}: {latency:12,} cycles x {repeat_times} = {layer_total:15,}")
    
    # 计算final层的延迟（只执行一次，但在decode阶段需要乘以batch_size）
    if stage == 'decode' and batch_size > 1:
        print(f"\n{'Final Layers (executed once, but scaled by batch_size=' + str(batch_size) + ')':^80}")
    else:
        print(f"\n{'Final Layers (executed once)':^80}")
    print(f"{'-'*80}")
    for layer_name, log_name in FINAL_LAYERS:
        log_file = os.path.join(log_dir, f"{log_name}.log")
        latency = read_latency_from_log(log_file)
        # 对于decode阶段，final层也需要乘以batch_size
        if stage == 'decode' and batch_size > 1:
            latency = latency * batch_size
        if quant_config:
            total_baseline += latency
            total_best += latency
        else:
            total_latency += latency
        
        if stage == 'decode' and batch_size > 1:
            print(f"{layer_name:20s}: {latency // batch_size:12,} cycles x {batch_size}  = {latency:15,}")
        else:
            print(f"{layer_name:20s}: {latency:12,} cycles x 1  = {latency:15,}")
    
    if quant_config:
        print(f"\n{'='*80}")
        print(f"Total Baseline Latency: {total_baseline:,} cycles")
        print(f"Total Best Latency:     {total_best:,} cycles")
        if total_baseline_act_lat1 > 0 or total_baseline_act_lat2 > 0:
            print(f"Baseline Activation Quant lat1: {total_baseline_act_lat1:,} cycles (extra)")
            print(f"Baseline Activation Quant lat2: {total_baseline_act_lat2:,} cycles (extra)")
        if total_best_act_lat1 > 0 or total_best_act_lat2 > 0:
            print(f"Best Activation Quant lat1:     {total_best_act_lat1:,} cycles (extra)")
            print(f"Best Activation Quant lat2:     {total_best_act_lat2:,} cycles (extra)")
        print(f"{'='*80}\n")
        return {
            'baseline': total_baseline, 
            'best': total_best,
            'baseline_act_lat1': total_baseline_act_lat1,
            'baseline_act_lat2': total_baseline_act_lat2,
            'best_act_lat1': total_best_act_lat1,
            'best_act_lat2': total_best_act_lat2
        }
    else:
        print(f"\n{'='*80}")
        print(f"Total Latency: {total_latency:,} cycles")
        print(f"{'='*80}\n")
        return {'fp16': total_latency}


if __name__ == "__main__":
    import sys
    import contextlib
    import io as _io

    output_dir = str(SCRIPT_DIR)

    # ── helpers ───────────────────────────────────────────────────────────────

    def _q_label(config):
        gk, gn = config['group_k'], config['group_n']
        if gk == 16 and gn == 1:
            q = 'q1'
        elif gk == 32 and gn == 1:
            q = 'q2'
        else:
            q = f'gk{gk}gn{gn}'
        return f"{config['method']} {q}(gk={gk},gn={gn})"

    def _total_lat(entry, version, method):
        """Total latency = main + lat1 (w_a only)."""
        lat = entry[version]
        if method == 'w_a':
            lat += entry.get(f'{version}_act_lat1', 0)
        return lat

    def _cname(config):
        return f"{config['method']}_{config['bitwidth']}_{config['group_k']}_{config['group_n']}"

    # ── fixed configuration ───────────────────────────────────────────────────

    model_list = [7, 34]
    batch_sizes = [1, 16]
    quant_configs = [
        {'method': 'w_a',    'bitwidth': 'D4S8', 'group_k': 16, 'group_n': 1},
        {'method': 'w_a',    'bitwidth': 'D4S8', 'group_k': 32, 'group_n': 1},
        {'method': 'w_only', 'bitwidth': 'D4S8', 'group_k': 16, 'group_n': 1},
        {'method': 'w_only', 'bitwidth': 'D4S8', 'group_k': 32, 'group_n': 1},
    ]

    # ── run all calculations silently ─────────────────────────────────────────

    print("Running calculations...", flush=True)
    results = {}
    with contextlib.redirect_stdout(_io.StringIO()):
        for model_size in model_list:
            r = {}
            r['fp16_prefill'] = calculate_e2e_latency(model_size, 'prefill')['fp16']
            r['fp16_decode'] = {
                bs: calculate_e2e_latency(model_size, 'decode', batch_size=bs)['fp16']
                for bs in batch_sizes
            }
            for config in quant_configs:
                cn = _cname(config)
                r[cn] = {
                    'prefill': calculate_e2e_latency(model_size, 'prefill', quant_config=config),
                    'decode':  {
                        bs: calculate_e2e_latency(model_size, 'decode', quant_config=config, batch_size=bs)
                        for bs in batch_sizes
                    },
                }
            results[model_size] = r
    print("Done.\n")

    # ── print final summary ───────────────────────────────────────────────────

    W   = [18, 46, 20, 20, 11, 13]
    TW  = sum(W)
    BAR = '─' * TW
    DBL = '═' * TW
    HDR = (f"{'Model':<{W[0]}}{'Config':<{W[1]}}"
           f"{'Total Latency':>{W[2]}}{'Baseline Total':>{W[3]}}"
           f"{'vs FP16':>{W[4]}}{'vs Baseline':>{W[5]}}")

    def _print_stage(stage, bs=None):
        title = 'PREFILL' if stage == 'prefill' else f'DECODE  BS={bs}'
        print(f'\n{DBL}')
        print(f'{title:^{TW}}')
        print(DBL)
        print(HDR)
        print(BAR)

        for model_size in model_list:
            r     = results[model_size]
            extra = EXTRA_LATENCY_34B if model_size == 34 else 0
            mlbl  = f"Llama2-{model_size}B"

            fp16_raw   = r['fp16_prefill'] if stage == 'prefill' else r['fp16_decode'][bs]
            fp16_total = fp16_raw + extra

            print(f"{mlbl:<{W[0]}}{'FP16':<{W[1]}}"
                  f"{fp16_total:>{W[2]},}{'—':>{W[3]}}"
                  f"{'1.00x':>{W[4]}}{'—':>{W[5]}}")

            for config in quant_configs:
                cn    = _cname(config)
                entry = r[cn]['prefill'] if stage == 'prefill' else r[cn]['decode'][bs]
                lbl   = _q_label(config)

                bl_total   = _total_lat(entry, 'baseline', config['method'])
                best_total = _total_lat(entry, 'best',     config['method'])

                spd_fp16 = fp16_total / best_total if best_total else 0.0
                spd_base = bl_total   / best_total if best_total else 0.0

                print(f"{'':>{W[0]}}{lbl + '  baseline':<{W[1]}}"
                      f"{bl_total:>{W[2]},}{'—':>{W[3]}}"
                      f"{'—':>{W[4]}}{'—':>{W[5]}}")
                print(f"{'':>{W[0]}}{lbl + '  best':<{W[1]}}"
                      f"{best_total:>{W[2]},}{bl_total:>{W[3]},}"
                      f"{spd_fp16:>{W[4]}.2f}x{spd_base:>{W[5]}.2f}x")

            if model_size != model_list[-1]:
                print(BAR)

    buf = _io.StringIO()
    sys.stdout = buf
    _print_stage('prefill')
    for bs in batch_sizes:
        _print_stage('decode', bs)
    sys.stdout = sys.__stdout__

    summary = buf.getvalue()
    print(summary)

    out_txt = os.path.join(output_dir, 'e2e_latency_results.txt')
    with open(out_txt, 'w') as f:
        f.write(summary)
    print(f"Text results saved to: {out_txt}")

    # ── save CSV ──────────────────────────────────────────────────────────────

    csv_file = os.path.join(output_dir, 'e2e_latency_summary.csv')
    with open(csv_file, 'w', newline='') as csvf:
        writer = csv.writer(csvf)

        hdr = ['Model', 'Stage', 'Batch_Size', 'FP16', 'Extra_Latency_34B']
        for config in quant_configs:
            cs = f"{config['method']}_{config['group_k']}"
            hdr += [f'{cs}_baseline', f'{cs}_best',
                    f'{cs}_baseline_lat1', f'{cs}_baseline_lat2',
                    f'{cs}_best_lat1',     f'{cs}_best_lat2']
        writer.writerow(hdr)

        all_stages = [('prefill', None)] + [('decode', bs) for bs in batch_sizes]
        for model_size in model_list:
            r     = results[model_size]
            extra = EXTRA_LATENCY_34B if model_size == 34 else 0
            for stage, bs in all_stages:
                fp16_raw = r['fp16_prefill'] if stage == 'prefill' else r['fp16_decode'][bs]
                row = [f'Llama2-{model_size}B', stage, bs or '', fp16_raw, extra]
                for config in quant_configs:
                    cn    = _cname(config)
                    entry = r[cn]['prefill'] if stage == 'prefill' else r[cn]['decode'][bs]
                    row += [
                        entry['baseline'],                 entry['best'],
                        entry.get('baseline_act_lat1', 0), entry.get('baseline_act_lat2', 0),
                        entry.get('best_act_lat1', 0),     entry.get('best_act_lat2', 0),
                    ]
                writer.writerow(row)

    print(f"CSV saved to: {csv_file}")

    # ── generate bar charts ───────────────────────────────────────────────────

    try:
        import matplotlib
        matplotlib.rcParams['font.family'] = 'DejaVu Sans'
        matplotlib.rcParams['font.size'] = 10
        import matplotlib.pyplot as plt

        PLOT_DIR = Path(output_dir) / "latency_plots"
        PLOT_DIR.mkdir(exist_ok=True)

        # colour scheme
        C_FP16_BASE,  C_FP16_EXTRA  = '#D5DBDB', '#5D6D7E'
        C_WONLY_BASE, C_WONLY_EXTRA = '#AED6F1', '#2874A6'
        C_WA_BASE,    C_WA_EXTRA    = '#A9DFBF', '#239B56'

        def _pf(v):
            try: return float(v)
            except: return 0.0

        def _plot_row(row):
            model      = row['Model']
            stage      = row['Stage']
            batch_size = row['Batch_Size']

            fp16_base  = _pf(row['FP16'])
            fp16_extra = _pf(row['Extra_Latency_34B'])

            bars = [{'base': fp16_base, 'extra': fp16_extra, 'type': 'fp16'}]
            for cs, ver in [('w_a_16','baseline'),('w_a_16','best'),
                            ('w_a_32','baseline'),('w_a_32','best'),
                            ('w_only_16','baseline'),('w_only_16','best'),
                            ('w_only_32','baseline'),('w_only_32','best')]:
                lat  = _pf(row[f'{cs}_{ver}'])
                lat1 = _pf(row[f'{cs}_{ver}_lat1'])
                lat2 = _pf(row[f'{cs}_{ver}_lat2'])
                base  = lat + lat2
                extra = (lat1 - lat2) if 'w_a' in cs else 0.0
                bars.append({'base': base, 'extra': extra,
                             'type': 'w_a' if 'w_a' in cs else 'w_only'})

            _, ax = plt.subplots(figsize=(14, 6), facecolor='none')
            ax.set_facecolor('none')
            for i, d in enumerate(bars):
                bc, ec = (C_FP16_BASE, C_FP16_EXTRA) if d['type'] == 'fp16' else \
                         (C_WA_BASE,   C_WA_EXTRA)   if d['type'] == 'w_a'  else \
                         (C_WONLY_BASE, C_WONLY_EXTRA)
                ax.bar([i], [d['base']],  0.7, color=bc, edgecolor='black', linewidth=0.5)
                if d['extra'] > 0:
                    ax.bar([i], [d['extra']], 0.7, bottom=[d['base']],
                           color=ec, edgecolor='black', linewidth=0.5)
            for spine in ax.spines.values():
                spine.set_visible(False)
            ax.set_xticks([])
            ax.set_yticks([])
            ax.set_ylim(0, max(d['base'] + d['extra'] for d in bars) * 1.1)

            bs_tag = '_BS'+str(batch_size) if batch_size else ''
            fname  = f"{model.replace('-','_')}_{stage}{bs_tag}.png"
            plt.tight_layout()
            plt.savefig(PLOT_DIR / fname, dpi=300, bbox_inches='tight', transparent=True)
            plt.close()
            return fname

        csv_rows = []
        with open(csv_file, 'r') as f:
            for row in csv.DictReader(f):
                csv_rows.append(row)

        n_plots = 0
        for row in csv_rows:
            _plot_row(row)
            n_plots += 1

        print(f"\n{n_plots} bar chart(s) saved to: {PLOT_DIR}")

    except ImportError:
        print("\nmatplotlib not available — skipping bar charts.")

    # ── summary ───────────────────────────────────────────────────────────────

#     print(f"""
# E2E latency results are printed above and written to:
#   Text summary : {out_txt}
#   CSV data     : {csv_file}

# Each row in the CSV corresponds to one bar chart saved under:
#   {Path(output_dir) / "latency_plots"}/
# File naming: <Model>_<stage>_BS<batch_size>.png
#   - prefill rows use BS_prefill; decode rows use BS1 / BS16.
#   - Each chart contains 9 bars: FP16 (grey), w_a q1/q2 baseline+best (green),
#     w_only q1/q2 baseline+best (blue). Stacked segments show the activation-
#     quantisation overhead (w_a only) on top of the base compute latency.
# """)

    # ── data-source validation ────────────────────────────────────────────────

    missing = []

    # 1. Single-operator latency table – existence + required entries
    if not QUANT_CSV_PATH.exists():
        missing.append(f"  - operator_latency_detailed.csv not found  [{QUANT_CSV_PATH}]")
    else:
        load_quant_latency_csv()
        for ms in model_list:
            mm_ops  = set(OP_NAME_MAPPING[ms]['prefill'].values())
            mvm_ops = set(OP_NAME_MAPPING[ms]['decode'].values())
            for cfg in quant_configs:
                method  = cfg['method']
                bitwidth = cfg['bitwidth']
                gk, gn  = str(cfg['group_k']), str(cfg['group_n'])
                # Prefill MM operators (no batch suffix)
                for op in mm_ops:
                    key = (f"{ms}B", f"{ms}B_{op}", method, bitwidth, gk, gn)
                    if key not in _quant_latency_cache:
                        missing.append(
                            f"  - CSV entry missing/empty: Llama2-{ms}B {op} prefill"
                            f"  {method} gk={gk},gn={gn}")
                # Decode MVM operators for each batch size
                for op in mvm_ops:
                    for bs in batch_sizes:
                        op_key = op if bs == 1 else f"{op}_B{bs}"
                        key = (f"{ms}B", f"{ms}B_{op_key}", method, bitwidth, gk, gn)
                        if key not in _quant_latency_cache:
                            missing.append(
                                f"  - CSV entry missing/empty: Llama2-{ms}B {op} decode bs={bs}"
                                f"  {method} gk={gk},gn={gn}")

    # 2. FP16 baseline log files – check each expected file and its content
    for ms in model_list:
        layers = LAYERS_7B_13B if ms in (7, 13) else LAYERS_34B
        for stg, stg_dir in (('prefill', 'prefill'), ('decode', 'decode_tk32')):
            log_dir = FP16_BASE_DIR / f"llama2_{ms}B_{stg_dir}" / "log"
            if not log_dir.exists():
                missing.append(f"  - FP16 log dir missing: {log_dir}")
                continue
            seen_logs = set()
            for _, log_name in layers + list(FINAL_LAYERS):
                if log_name in seen_logs:
                    continue
                seen_logs.add(log_name)
                log_file = log_dir / f"{log_name}.log"
                if not log_file.exists():
                    missing.append(
                        f"  - FP16 log file missing: {log_file.name}"
                        f"  (Llama2-{ms}B {stg})")
                else:
                    content = log_file.read_text(errors='replace')
                    if 'baseline result:' not in content:
                        missing.append(
                            f"  - FP16 log has no 'baseline result': {log_file.name}"
                            f"  (Llama2-{ms}B {stg})")

    # 3. Activation-quantisation latency cache (lat1 / lat2) – check per operator
    #    The log file should contain all 4 configs (w_a + w_only × gk16 + gk32);
    #    check every expected key, not just w_a.
    load_quant_act_latency_from_logs()
    all_method_gk_gn = [(cfg['method'], cfg['group_k'], cfg['group_n'])
                        for cfg in quant_configs]
    for ms in model_list:
        unique_ops: set = set()
        for stg in ('prefill', 'decode'):
            for op in OP_NAME_MAPPING[ms][stg].values():
                unique_ops.add(op)
        for op in unique_ops:
            op_key = f"{op}_1" if 'MVM' in op else op
            for method, gk, gn in all_method_gk_gn:
                key = (f"{ms}B", f"{ms}B_{op_key}", method, 'D4S8', str(gk), str(gn))
                if key not in _quant_act_latency_cache:
                    missing.append(
                        f"  - Quant-act lat1/lat2 missing: Llama2-{ms}B {op}"
                        f"  {method} gk={gk},gn={gn}  (looked up as {op_key})")

    if missing:
        print("\n" + "!" * 80)
        print("WARNING: The following data sources are missing or have incomplete results.")
        print("Computed results may be inaccurate or contain zero-filled placeholders:")
        for m in missing:
            print(m)
        print("!" * 80)
